---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Gathering Facts
      become: false
      setup:
        gather_subset:
          - '!all'
          - network
          - hardware
    - name: Update Apt Cache
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family | lower == 'debian'
      changed_when: false
  roles:
    - role: hwwilliams.logwatch
